language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - pip install networkx
  - pip install jedi
  - pip install delorean
install:
  - travis_retry python setup.py build develop
script: 
  #- travis_wait ./run_tests.py
  - travis_wait ./run_tests.py --tonose
  - travis_wait py.test
after_failure: 
  - cat failed_doctests.txt
cache: 
    apt: true
    directories:
        - $HOME/.pip-cache
