language: python
python:
  - "2.7"
  - "3.4"
install:
  - travis_retry python setup.py build develop
script: 
  #- travis_wait ./run_tests.py
  - travis_wait ./run_tests.py --tonose
  - travis_wait py.test
after_failure: 
  - cat failed_doctests.txt
